//////////////////////////////// html exercices/////////////////////////////////////////////

const code1 =
  '<!DOCTYPE html>\n<html lang="en"> \n <head> \n<title>ex1</title>\n <style> \n  h1,   h2,   h3,   h4,   p {color: aliceblue; } \nbody{background-color: black;}\n</style>\n</head>\n<body >\n<h1>Titre de l`entète de la page</h1>\n<br /><div class="links">\n<a href="#">Accueil</a><br />\n<a href="#">Services</a><br />\n<a href="#">Partenaires</a>\n<br /><a href="#">Contact</a>\n</div> \n<br /> <h2>Titre de la section</h2> \n<br />\n <section>  \n <h3>Titre de l`article1</h3> <h4>contenu de l`article1</h4><br />\n <h3>Titre de l`article2</h3> <h4>contenu de l`article2</h4>\n</section>\n<br />\n<p>@2020 All Rights Reserved</p>\n</body>\n</html>';
const code2 =
  '<!DOCTYPE html>\n<html lang="en"> \n<head>\n<title>ex2</title>\n<style> \n .container {margin: 15% 15%; border: solid;padding: 3rem; width: 30%; }\n.circle { margin-left: 40%; height: 50px;width: 50px;background-color: #555;border-radius: 50%;} \n.rectangle { margin-left: 70%; margin-top: 10%; height: 50px; width: 100px; background-color: #555; }\n.triangle-up { margin-left: 10%; width: 0; height: 0;border-left: 25px solid transparent;border-right: 25px solid transparent;border-bottom: 50px solid #555; } \n</style>\n </head> \n<body>\n<div class="container"> \n<a href="cercle.com"><div class="circle"></div></a> \n<a href="rectangle.com"> <div class="rectangle"></div></a>\n <a href="triangle.com"><div class="triangle-up"></div></a> \n</div>\n</body>\n</html>';
const code3 =
  '<!DOCTYPE html>\n<html lang="en">\n<head> \n <title>ex3</title> \n</head> \n<body>  \n <div style="margin-top: 5rem; margin-left: 3rem"> \n    <button style="border: double black; color: red">  PREFIX USUELS EN METROLOGIE  </button>\n<p>Quand le nombre d`unités est trop grand on utilise des préfixes:</p>\n<table style="text-align: center; margin-left: 20%" border="2">\n<tr>\n<td style="text-align: center" colspan="3"><b>Multiple</b></td>\n<td style="text-align: center"><b>Exemple</b></td>\n</tr>\n <tr>\n<td><b>Préfixe</b></td>\n<td><b>Symbole</b></td>\n<td><b>Multiplicateur</b></td>\n<td rowspan="5">  1 500 000 000 octets <br />  c`est 1,5 Go=1500 Mo</td>\n</tr> \n<tr>\n<td>téra</td><td>T</td>\n<td>10<sup>12</sup></td>\n</tr>\n<tr>\n  <td>giga</td> \n <td>G</td>  \n<td>10<sup>9</sup></td>\n</tr>\n<tr>  \n<td>méga</td> \n <td>M</td> \n <td>10<sup>6</sup></td> \n</tr> \n<tr> \n<td>kilo</td>\n<td>K</td> \n<td>10<sup>3</sup></td>\n</tr>\n</table>\n</div>\n</body>\n</html>';
const code4 =
  '<!DOCTYPE html>\n<head>\n<title>ex4</title>\n</head>\n<style>\nbody{ color: navy;}\n</style>\n<body>\n<h1> <font color="blue"  > <center> Développement WEB </font></center> </h1>\n<ul type="disc">\n<li> <a href="#P1" > le web </a> </li>\n<li> <a href="#P2"> les serviuces web</a></li>\n<li><a href="#P3">liste d`outils d`internet</a></li> \n</ul>\n<h2> <a name="P1"> Le Web</a></h2>\n<p>Systeme hypertexte publique fonctionnant sur internet et qui permet de consulter avec un navigateur des pages mises en ligne dans des sites</p>\n<h2><a name="P2">les services web</a></h2>\n<p> Les services de l`internet sont offertes par les serveurs présentes sur l`internet:</p>\n<ol type="1" start="1"> \n<li>web(document hypertextes</li><li>corrier éléctronique(email)</li>\n<li>messagerie instantané</li>\n<li>forums de discussion</li>\n<li> Téléchargements des fichiers</li>\n</ol>\n<h2><a name="P3">Liste d`outils d`internet</a></h2>\n<table border="1">\n<tr>\n<td rowspan="3" >Outils de présentation</td> \n<TD colspan="2"><A href="http://cyberzoide.developpez.com/html/"> HTML</A></TD>\n<tr>\n<td colspan="2"><a href="http://xml.developpez.com/cours/">XML</a> </td>\n</tr>\n<tr>\n<td colspan="2"><a href="http://css.developpez.com/cours/">css</a></td>\n  </tr>\n<tr><td rowspan="2">outils de programmation</td>\n<td><a href="http://javascript.developpez.com/cours"><img src="../../images/js.png" width="80"></a></td>\n<td>Java script</td></tr>\n <tr>\n<td><a href="http://chgi.developpez.com/java/applet/"><img src="../../images/applet.png" width="80"></a></td>\n<td>applet java</td> \n</tr>\n</table>\n</body>';
const code5 =
  '<!DOCTYPE html>\n<html>\n<head>\n<title></title>\n</head>\n<body>\n<form >\n<fieldset>\n<legend>Votre identité</legend>\n<ol>\n<li>\nNom <input type="text" name="nom" placeholder="Prénom et nom">\n<br>\n</li>\n<li>\nEmail <input type="text" name="email" placeholder="exemple@domaine.com">	\n</li>\n<li>\nTéléphone <input type="text" name="tel" placeholder="+21600000000">\n</li>\n</ol>\n</fieldset>\n</form>\n<form >\n<fieldset>\n<legend>VAdresse de livraison</legend>\n<ol>\n<li>\nAdresse <textarea></textarea>\n</li>\n	<li>\nCode postal <input type="number" name="code">\n	</li>\n<li>\nPays <input type="text" name="pays" placeholder="">\n</li>\n</ol>\n</fieldset>\n</form>\n<form >\n<fieldset>\n<legend>informations CB</legend>\n<ol>\n<li>\n<form>\n<fieldset>\n<legend>Type de carte bancaire</legend>\n<ol>\n<li>\n<input id="rad1" type="radio" name="carte">\n<label for="rad1">VISA</label>\n</li>\n<li>\n<input id="rad2" type="radio" name="carte">\n<label for="rad2">AmEx</label>\n</li>\n<li>\n<input id="rad3" type="radio" name="carte">\n<label for="rad3">Mastercard</label>\n</li>\n</ol>\n</fieldset>\n</form>\n</li>\n<li>\nNum de carte <input type="number" name="NumCarte">\n	</li>\n<li>\nCode sécurité <input type="number" name="codeSec" placeholder="">\n</li>\n<li>\nNom du poteur  <input type="text" name="codeSec" placeholder="Mème nom que sur la carte">\n</li>\n</ol>\n</fieldset>\n</form>\n<form>\n<fieldset>\n<input disabled="true" type="submit" value="J`achète!"   style="color: blue;">\n</input>\n</fieldset>\n</form>\n</body>\n</html>';
//////////////////////////////////   css exercices /////////////////////////////////////
const code6 =
  '<html>\n<head>\n <style>\nbody {  color: blue;}\nh1 {  color: green;}\n.h1 {color: blue;}\nol[start] li { color: purple;}\n#h2 { color: yellow;}\nli:first-child {  color: orange;}\n li[title^="sel"] { color: red;}\n</style>\n</head>\n<body>\n<h1>texte [1]</h1>\n<ul>\n<li>texte [2]</li>\n<li>texte [3]</li>\n</ul> \n<h2 id="h2" title="selection">texte [4]</h2>\n <ul>\n   <li>texte [5]</li> \n  <li class="h1" title="selecteur">\ntexte [6] <ol start="2"><li>texte [7]</li></ol></li>\n</ul>\n</body>\n</html>';
const code7 =
  '<!DOCTYPE html>\n<head>\n<title>ex4</title>\n</head>\n<style>\n  body{ color: navy;font-family: Helvetica;background-image: url("../../images/sky.jpg");background-repeat: no-repeat;background-size: cover;}\ntable{ border-radius: 5px;}\nh2 {font-family:Arial;}\nh1{color:white;background-color: navy;text-shadow: 5px 5px 5px gray;}\na:link {color: navy;}\na:visited{color: brown;}\n</style>\n<body>\n<h1> <font color="blue"  > <center> Développement WEB </font></center> </h1>\n<ul type="disc">\n<li> <a href="#P1" > le web </a> </li>\n<li> <a href="#P2"> les serviuces web</a></li>\n<li><a href="#P3">liste d`outils d`internet</a></li> \n</ul>\n<h2> <a name="P1"> Le Web</a></h2>\n<p>Systeme hypertexte publique fonctionnant sur internet et qui permet de consulter avec un navigateur des pages mises en ligne dans des sites</p>\n<h2><a name="P2">les services web</a></h2>\n<p> Les services de l`internet sont offertes par les serveurs présentes sur l`internet:</p>\n<ol type="1" start="1"> \n<li>web(document hypertextes</li><li>corrier éléctronique(email)</li>\n<li>messagerie instantané</li>\n<li>forums de discussion</li>\n<li> Téléchargements des fichiers</li>\n</ol>\n<h2><a name="P3">Liste d`outils d`internet</a></h2>\n<table border="1">\n<tr>\n<td rowspan="3" >Outils de présentation</td> \n<TD colspan="2"><A href="http://cyberzoide.developpez.com/html/"> HTML</A></TD>\n<tr>\n<td colspan="2"><a href="http://xml.developpez.com/cours/">XML</a> </td>\n</tr>\n<tr>\n<td colspan="2"><a href="http://css.developpez.com/cours/">css</a></td>\n  </tr>\n<tr><td rowspan="2">outils de programmation</td>\n<td><a href="http://javascript.developpez.com/cours"><img src="../../images/js.png" width="80"></a></td>\n<td>Java script</td></tr>\n <tr>\n<td><a href="http://chgi.developpez.com/java/applet/"><img src="../../images/applet.png" width="80"></a></td>\n<td>applet java</td> \n</tr>\n</table>\n</body>';

const code8 =
  '<!DOCTYPE html>\n<head>\n<title>ex3</title>\n</head>\n<style>\nimg {position: absolute;} \n#one{ top:50px; left: 400px;transform: rotate(-10deg) translateX(10px);}\n#two{ top:150px; left: 400px;transform: rotate(5deg) translateX(10px);}\n#three{top:250px;left: 400px;transform: rotate(-3deg) translateX(10px);}\n#four{top:50px;left: 500px;transform: rotate(-3deg) translateX(-10px);}\n#fifth{ top:150px;left: 500px;transform: rotate(10deg) translateX(-10px);}\n#six{top:250px;left: 500px;}\nimg:hover  {opacity: 1; position:relative;z-index:10; border-top: 2px solid white;border-bottom: 2px solid white;\nborder-left: 2px solid white;border-right: 2px solid white;box-shadow: 5px 5px 5px black;\ntransition: .5s ease;display: block;}\n.middle {  transition: .5s ease;  opacity: 0;  position: absolute;  transform: translate(-50%, -50%); \n -ms-transform: translate(-50%, -50%);}\nimg:hover .middle {opacity: 1;}\n.text {  color: black;}\nh1{  animation-name: example;  animation-duration: 4s;}\n@keyframes example {0%   {color: red;}25%  {color: yellow;}  50%  {color: blue;}  100% {color: green;}}  \n      </style>\n</head>   \n <body>  \n <div class="container">\n <img id="one" src="../../images/1.jpg" width="100px" height="100px">\n<div class="middle">\n<div class="text">Titre</div>\n</div>    \n    <img  id="two" src="../../images/2.jpg"width="100px" height="100px">  \n <img id="three" src="../../images/3.jpg"width="100px" height="100px">  \n <img id="four" src="../../images/4.jpg"width="100px" height="100px"> \n<img id="fifth"src="../../images/5.jpg"width="100px" height="100px"> \n <img id="six" src="../../images/6.jpg"width="100px" height="100px"\n </div>\n</body>\n</html>';
const code9 = "";
const tab = [code1, code2, code3, code4, code5, code6, code7, code8, code9];
function setSrcCode(code) {
  if (code) {
    localStorage.setItem("codeExemple", tab[code - 1]);
  }
}
